function Table() {
    return (
        <div className="grid">
            <div className="block reactive-nonmetals" id="hydrogen">H</div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block noble-gases" id="helium">He</div>

            <div className="block alkali-metals">Li</div>
            <div className="block alkaline-earth-metals">Be</div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block metalloids">B</div>
            <div className="block reactive-nonmetals">C</div>
            <div className="block reactive-nonmetals">N</div>
            <div className="block reactive-nonmetals">O</div>
            <div className="block reactive-nonmetals">F</div>
            <div className="block noble-gases">Ne</div>

            <div className="block alkali-metals">Na</div>
            <div className="block alkaline-earth-metals">Mg</div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block post-transition-metals">Al</div>
            <div className="block metalloids">Si</div>
            <div className="block reactive-nonmetals">P</div>
            <div className="block reactive-nonmetals">S</div>
            <div className="block reactive-nonmetals">Cl</div>
            <div className="block noble-gases">Ar</div>

            <div className="block alkali-metals">K</div>
            <div className="block alkaline-earth-metals">Ca</div>
            <div className="block transition-metals">Sc</div>
            <div className="block-empty"></div>
            <div className="block transition-metals">Ti</div>
            <div className="block transition-metals">V</div>
            <div className="block transition-metals">Cr</div>
            <div className="block transition-metals">Mn</div>
            <div className="block transition-metals">Fe</div>
            <div className="block transition-metals">Co</div>
            <div className="block transition-metals">Ni</div>
            <div className="block transition-metals">Cu</div>
            <div className="block transition-metals">Zn</div>
            <div className="block post-transition-metals">Ga</div>
            <div className="block metalloids">Ge</div>
            <div className="block metalloids">As</div>
            <div className="block reactive-nonmetals">Se</div>
            <div className="block reactive-nonmetals">Br</div>
            <div className="block noble-gases">Kr</div>

            <div className="block alkali-metals">Rb</div>
            <div className="block alkaline-earth-metals">Sr</div>
            <div className="block transition-metals">Y</div>
            <div className="block-empty"></div>
            <div className="block transition-metals">Zr</div>
            <div className="block transition-metals">Nb</div>
            <div className="block transition-metals">Mo</div>
            <div className="block transition-metals">Tc</div>
            <div className="block transition-metals">Ru</div>
            <div className="block transition-metals">Rh</div>
            <div className="block transition-metals">Pd</div>
            <div className="block transition-metals">Ag</div>
            <div className="block transition-metals">Cd</div>
            <div className="block post-transition-metals">In</div>
            <div className="block post-transition-metals">Sn</div>
            <div className="block metalloids">Sb</div>
            <div className="block metalloids">Te</div>
            <div className="block reactive-nonmetals">I</div>
            <div className="block noble-gases">Xe</div>

            <div className="block alkali-metals">Cs</div>
            <div className="block alkaline-earth-metals">Ba</div>
            <div className="block lanthanides">La</div>
            <div className="block-empty"></div>
            <div className="block transition-metals">Hf</div>
            <div className="block transition-metals">Ta</div>
            <div className="block transition-metals">W</div>
            <div className="block transition-metals">Re</div>
            <div className="block transition-metals">Os</div>
            <div className="block transition-metals">Ir</div>
            <div className="block transition-metals">Pt</div>
            <div className="block transition-metals">Au</div>
            <div className="block transition-metals">Hg</div>
            <div className="block post-transition-metals">Tl</div>
            <div className="block post-transition-metals">Pb</div>
            <div className="block post-transition-metals">Bi</div>
            <div className="block post-transition-metals">Po</div>
            <div className="block post-transition-metals">At</div>
            <div className="block noble-gases">Rn</div>

            <div className="block alkali-metals">Fr</div>
            <div className="block alkaline-earth-metals">Ra</div>
            <div className="block actinides">Ac</div>
            <div className="block-empty"></div>
            <div className="block transition-metals">Rf</div>
            <div className="block transition-metals">Db</div>
            <div className="block transition-metals">Sg</div>
            <div className="block transition-metals">Bh</div>
            <div className="block transition-metals">Hs</div>
            <div className="block unknown-properties">Mt</div>
            <div className="block unknown-properties">Ds</div>
            <div className="block unknown-properties">Rg</div>
            <div className="block unknown-properties">Cn</div>
            <div className="block unknown-properties">Nh</div>
            <div className="block unknown-properties">Fl</div>
            <div className="block unknown-properties">Mc</div>
            <div className="block unknown-properties">Lv</div>
            <div className="block unknown-properties">Ts</div>
            <div className="block unknown-properties">Og</div>

            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>

            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>

            <div className="block lanthanides">Ce</div>
            <div className="block lanthanides">Pr</div>
            <div className="block lanthanides">Nd</div>
            <div className="block lanthanides">Pm</div>
            <div className="block lanthanides">Sm</div>
            <div className="block lanthanides">Eu</div>
            <div className="block lanthanides">Gd</div>
            <div className="block lanthanides">Tb</div>
            <div className="block lanthanides">Dy</div>
            <div className="block lanthanides">Ho</div>
            <div className="block lanthanides">Er</div>
            <div className="block lanthanides">Tm</div>
            <div className="block lanthanides">Yb</div>
            <div className="block lanthanides">Lu</div>

            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block actinides">Th</div>
            <div className="block actinides">Pa</div>
            <div className="block actinides">U</div>
            <div className="block actinides">Np</div>
            <div className="block actinides">Pu</div>
            <div className="block actinides">Am</div>
            <div className="block actinides">Cm</div>
            <div className="block actinides">Bk</div>
            <div className="block actinides">Cf</div>
            <div className="block actinides">Es</div>
            <div className="block actinides">Fm</div>
            <div className="block actinides">Md</div>
            <div className="block actinides">No</div>
            <div className="block actinides">Lr</div>
        </div>
    );
}

export default Table;