function Table() {
    return (
        <div className="grid">
            <div className="block reactive-nonmetals" id="hydrogen">H</div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block noble-gases" id="helium">He</div>

            <div className="block alkali-metals"></div>
            <div className="block alkaline-earth-metals"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block metalloids"></div>
            <div className="block reactive-nonmetals"></div>
            <div className="block reactive-nonmetals"></div>
            <div className="block reactive-nonmetals"></div>
            <div className="block reactive-nonmetals"></div>
            <div className="block noble-gases"></div>

            <div className="block alkali-metals"></div>
            <div className="block alkaline-earth-metals"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block post-transition-metals"></div>
            <div className="block metalloids"></div>
            <div className="block reactive-nonmetals"></div>
            <div className="block reactive-nonmetals"></div>
            <div className="block reactive-nonmetals"></div>
            <div className="block noble-gases"></div>

            <div className="block alkali-metals"></div>
            <div className="block alkaline-earth-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block-empty"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block post-transition-metals"></div>
            <div className="block metalloids"></div>
            <div className="block metalloids"></div>
            <div className="block reactive-nonmetals"></div>
            <div className="block reactive-nonmetals"></div>
            <div className="block noble-gases"></div>

            <div className="block alkali-metals"></div>
            <div className="block alkaline-earth-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block-empty"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block post-transition-metals"></div>
            <div className="block post-transition-metals"></div>
            <div className="block metalloids"></div>
            <div className="block metalloids"></div>
            <div className="block reactive-nonmetals"></div>
            <div className="block noble-gases"></div>

            <div className="block alkali-metals"></div>
            <div className="block alkaline-earth-metals"></div>
            <div className="block lanthanides"></div>
            <div className="block-empty"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block post-transition-metals"></div>
            <div className="block post-transition-metals"></div>
            <div className="block post-transition-metals"></div>
            <div className="block post-transition-metals"></div>
            <div className="block post-transition-metals"></div>
            <div className="block noble-gases"></div>

            <div className="block alkali-metals"></div>
            <div className="block alkaline-earth-metals"></div>
            <div className="block actinides"></div>
            <div className="block-empty"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block transition-metals"></div>
            <div className="block unknown-properties"></div>
            <div className="block unknown-properties"></div>
            <div className="block unknown-properties"></div>
            <div className="block unknown-properties"></div>
            <div className="block unknown-properties"></div>
            <div className="block unknown-properties"></div>
            <div className="block unknown-properties"></div>
            <div className="block unknown-properties"></div>
            <div className="block unknown-properties"></div>
            <div className="block unknown-properties"></div>

            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>

            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block lanthanides"></div>
            <div className="block lanthanides"></div>
            <div className="block lanthanides"></div>
            <div className="block lanthanides"></div>
            <div className="block lanthanides"></div>
            <div className="block lanthanides"></div>
            <div className="block lanthanides"></div>
            <div className="block lanthanides"></div>
            <div className="block lanthanides"></div>
            <div className="block lanthanides"></div>
            <div className="block lanthanides"></div>
            <div className="block lanthanides"></div>
            <div className="block lanthanides"></div>
            <div className="block lanthanides"></div>
            <div className="block-empty"></div>

            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block-empty"></div>
            <div className="block actinides"></div>
            <div className="block actinides"></div>
            <div className="block actinides"></div>
            <div className="block actinides"></div>
            <div className="block actinides"></div>
            <div className="block actinides"></div>
            <div className="block actinides"></div>
            <div className="block actinides"></div>
            <div className="block actinides"></div>
            <div className="block actinides"></div>
            <div className="block actinides"></div>
            <div className="block actinides"></div>
            <div className="block actinides"></div>
            <div className="block actinides"></div>
        </div>
    );
}

export default Table;